config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'tasks', to: 'tasks#index'

  post 'tasks', to: 'tasks#create'
  get 'tasks/new', to: 'tasks#new'

  get 'tasks/:id', to: 'tasks#show', as: 'task'

  get 'tasks/:id/edit', to: 'tasks#edit', as: 'task_edit'
  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(tasks_params)
    @task.save

    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(tasks_params)

    redirect_to task_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

  def tasks_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1><%= @task.title %></h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

<%= link_to 'Back to the task', task_path %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<h3>welcome to the task manager</h3>

<ul>
  <% @tasks.each do |task| %>
    <li class="p-3">
      <%= link_to task.title, task_path(task)%>
      <%= link_to 'Delete this task', task_path(task), method: :delete, data: {confirm: "Are you sure?"} %>
    </li>
  <% end %>
</ul>

<%= link_to 'Add a new task', tasks_new_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

<%= link_to 'Back to all tasks', tasks_path %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p><%= @task.details %></p>


<%= link_to 'Edit the task', task_edit_path %>
<%= link_to 'Back to all tasks', tasks_path %>